### ISSUE TITLE
Add support so ban plugin can handle new speed and error limits built into Geeklog Core

### ISSUE THREAD

**Issue by eSilverStrike** [Geeklog-Plugins/ban#17]
Add support for error limits built into Geeklog Core.

Will need config options to enable/disable and max limits???

New function called plugin_onSpeeding_ban($type, $property, $last)
Type = 'login', 'submit', 'error-404', 'error-spam'

For more info see: https://github.com/Geeklog-Core/geeklog/issues/1030

**Comment by eSilverStrike** [comment]
@mystralkk I am thinking of turning at least the error limits into $_CONF options so the ban plugin can overwrite them if the user wants to change the value

This would be the same for the SPEED_LIMIT_MAX_ERROR_foo constants as some users may be worried about banning Google bot if the settings are to low.

I was thinking of just hard coding them into lib-plugins and then the ban could overwrite if needed the config values. Maybe I should take the time and actually add them to the Geeklog Configuration...


// Constants for the max number of allowed tries within speed limit (since Geeklog 2.2.2)
const SPEED_LIMIT_MAX_COMMENT = 1;
const SPEED_LIMIT_MAX_ERROR_403 = 1;    // Illegal access to admin screen
const SPEED_LIMIT_MAX_ERROR_404 = 5;
const SPEED_LIMIT_MAX_ERROR_SPAM = 1;
const SPEED_LIMIT_MAX_LIKES = 1;
const SPEED_LIMIT_MAX_MAIL = 1;
const SPEED_LIMIT_MAX_PASSWORD = 1;
const SPEED_LIMIT_MAX_PINGBACK = 1;
const SPEED_LIMIT_MAX_SUBMIT = 1;
const SPEED_LIMIT_MAX_TRACKBACK = 1;

// Constants for the window used in COM_clearSpeedlimit
const SPEED_LIMIT_WINDOW_ERROR_403 = 60;
const SPEED_LIMIT_WINDOW_ERROR_404 = 60;
const SPEED_LIMIT_WINDOW_ERROR_SPAM = 60;

**Comment by mystralkk** [comment]
Sounds goods to me.  I am not sure if converting these constants into config values is worth the time and trouble.
